name: wtech_ecommerce
description: an ecommerce application for selling electronic prodcuts 

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash.png
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter

   # Project Packages
  # =======================================
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2 # for Responsive screen
  shared_preferences: ^2.0.15 # for lacal cache 
  flutter_svg: ^1.1.3 # svg icons viewer
  # Firebase services
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_storage: ^10.3.4
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.0
  email_auth: ^1.0.0
  #state management
  flutter_bloc: ^8.0.1
  # presisting states
  hydrated_bloc: ^8.1.0
  # for form validations
  reactive_forms: ^14.1.0 
  # for rating prodcuts
  flutter_rating_bar: ^4.0.1
  # for date formatting
  intl: ^0.17.0
  # for caching images locally
  cached_network_image: ^3.2.1
  #splash screen
  flutter_native_splash: ^2.2.8
  # Functional Programmming
  dartz: ^0.10.1
  #value equatable
  equatable: ^2.0.5
  # lottie animations
  lottie: ^1.4.2
# animations delay 
  delayed_display: ^2.0.0
  get_it: ^7.2.0
  ## Fake Firebase 
  fake_cloud_firestore: ^1.3.1
  google_sign_in_mocks: ^0.2.1
  firebase_auth_mocks: ^0.8.5+1
  # Navigator 2.0
  go_router: ^4.4.1
  # paths for uploading files
  path_provider: ^2.0.11
  # for choosing images from gallery
  image_picker: ^0.8.5+3

 

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.0
  build_runner: ^2.2.0


flutter:
  uses-material-design: true
# To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
  
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir_Book.ttf
          weight: 400
        - asset: assets/fonts/Avenir_Regular.ttf
          weight: 400
        - asset: assets/fonts/Avenir_Heavey.ttf
          weight: 300

  