// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1hPPPU8sdSBwaAsJvxVcgcoIcX_0AeA',
    appId: '1:347495944682:web:0196162e2ad3395d38a293',
    messagingSenderId: '347495944682',
    projectId: 'wtech-98830',
    authDomain: 'wtech-98830.firebaseapp.com',
    storageBucket: 'wtech-98830.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEJSnv0sEIPWWDdvsK9jzz6DaMfhBEuk',
    appId: '1:347495944682:android:808ad1edd18ceda738a293',
    messagingSenderId: '347495944682',
    projectId: 'wtech-98830',
    storageBucket: 'wtech-98830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEADxOTzKcL8OapDCfDkxJ95wI1zBxnyM',
    appId: '1:347495944682:ios:437e4fa0cc6e638b38a293',
    messagingSenderId: '347495944682',
    projectId: 'wtech-98830',
    storageBucket: 'wtech-98830.appspot.com',
    iosClientId: '347495944682-g37ves0rrcqe2001l8gf6ggt7jjcea3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtechEcommerce',
  );
}
